routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get( '/paysera/redirect/{id}', 'PayseraGatewayController@redirect' )->name( 'paysera-redirect' );
Route::get( '/paysera/callback', 'PayseraGatewayController@callback' )->name( 'paysera-callback' );
Route::get( '/paysera/uzsakymas-pavyko', 'PayseraGatewayController@success');
Route::get( '/paysera/uzsakymas-nepavyko', function () {
	echo "uzsakymas nepavyko";
} );
Route::get( '/', 'ProductController@index' )->name( 'shop' );

Auth::routes();

Route::get( '/home', 'HomeController@index' )->name( 'home' );

Route::resource( 'products', 'ProductController' );

Route::resource( 'order', 'OrderController' );


Route::get( '/checkout', 'CartController@checkout' )->name( 'cart.checkout' );
Route::resource( 'cart', 'CartController' );

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;

class CartController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //


		$products = User::cartItems();
		$cartTotal = User::cartValue();


		return view('cart.index', [
			'products' => $products,
			'cartTotal' => $cartTotal
		]);
    }

    public function checkout() {

    	return view('cart.checkout');
	}

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //


		$product = Product::findOrFail($request->input('product_id'));


		// gauname esamus krepselio duomenis is sessijos
		$cart = session()->get('cart');


		// patikriname ar krepselis jau yra sukurtas
		if($cart == null) {
			// jei vartotojas neturi sukurto krepselio, sukuriame ji kaip tuscia masyva
			$cart = [];
		}

		/* patikriname ar pasirinkta preke jau ideta i krepseli */
		if(array_key_exists($product->id, $cart)) {
			// jei preke egzistuoja, tai prie jos kiekio pridedame vieneta
			$cart[$product->id]['quantity']++;
		} else {
			// jei preke neegzistuoja tada sukuriame nauja masyvo elementa
			$cart[$product->id] = [
				'id' => $product->id,
				'title' => $product->title,
				'image' => $product->image,
				'price' => $product->price,
				'quantity' => 1
			];
		}


		session()->put('cart', $cart);

		return redirect()->route('cart.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/cart/checkout.blade.php
@extends('layouts.shop')


@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h1>Checkout information </h1>
                <form action="{{ route('order.store') }}" method="post">
                    @csrf

                   <div class="form-group">
                       <label>Full name</label>
                       <input required type="text" name="full_name" class="form-control">
                   </div>

                    <div class="form-group">
                        <label>Email</label>
                        <input required type="email" name="email" class="form-control">
                    </div>

                    <div class="form-group">
                        <label>Address </label>
                        <input required type="text" name="delivery_address" class="form-control">
                    </div>

                    <input type="submit" value="BUY" class="btn btn-primary btn-block">

                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/cart/index.blade.php
@extends('layouts.shop')


@section('content')
    <div class="cart-main-area ptb--100 bg__white">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <form action="#">
                        <div class="table-content table-responsive">
                            <table>
                                <thead>
                                <tr>
                                    <th class="product-thumbnail">products</th>
                                    <th class="product-name">name of products</th>
                                    <th class="product-price">Price</th>
                                    <th class="product-quantity">Quantity</th>
                                    <th class="product-subtotal">Total</th>
                                    <th class="product-remove">Remove</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($products as $product)
                                    <tr>
                                        <td class="product-thumbnail">
                                            <a href="{{ route('products.show', [$product->id]) }}">
                                                <img src="{{ $product->image }}" alt="product img">
                                            </a>
                                        </td>
                                        <td class="product-name">
                                            <a href="{{ route('products.show', [$product->id]) }}">
                                                {{ $product->title }}
                                            </a>
                                            <ul class="pro__prize">
                                                <li>{{ $product->price }}€</li>
                                            </ul>
                                        </td>
                                        <td class="product-price">
                                            <span class="amount">
                                                {{ $product->price * $product->quantity }}€
                                            </span>
                                        </td>
                                        <td class="product-quantity">
                                            <input type="number" value="{{ $product->quantity }}">
                                        </td>
                                        <td class="product-subtotal">
                                            {{ $product->price * $product->quantity }}€
                                        </td>
                                        <td class="product-remove"><a href="#"><i class="icon-trash icons"></i></a></td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <div class="buttons-cart--inner">
                                    <div class="buttons-cart">
                                        <a href="{{ route('shop') }}">Continue Shopping</a>
                                    </div>
                                    <div class="buttons-cart checkout--btn">
                                        <a href="#">update</a>
                                        <a href="{{ route('cart.checkout') }}">checkout</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 col-sm-12 col-xs-12">

                            </div>
                            <div class="col-md-6 col-sm-12 col-xs-12 smt-40 xmt-40">
                                <div class="htc__cart__total">
                                    <h6>cart total</h6>
                                    <div class="cart__desk__list">
                                        <ul class="cart__desc">
                                            <li>cart total</li>
                                            <li>shipping</li>
                                        </ul>
                                        <ul class="cart__price">
                                            <li>{{ $cartTotal }}€</li>
                                            <li>0</li>
                                        </ul>
                                    </div>
                                    <div class="cart__total">
                                        <span>order total</span>
                                        <span>{{ $cartTotal }}€</span>
                                    </div>
                                    <ul class="payment__btn">
                                        <li class="active"><a href="#">payment</a></li>
                                        <li><a href="{{ route('shop') }}">continue shopping</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection